### ISSUE TITLE
SequelizeDatabaseError]: BLOB/TEXT column 'iss' used in key specification without a key length

### ISSUE THREAD

**Issue by jadavbheda** [Cvmcosta/ltijs-sequelize#2] opened 2021-03-15 05:52 UTC
Hi There, 

I am trying to use Ltijs sample server app using Ltijs-sequelize plugin with MySql Database.

But when I start `yarn start` I get below error: 
DatabaseError [SequelizeDatabaseError]: BLOB/TEXT column 'iss' used in key specification without a key length

I think it caused by trying to index `iss` which is a TEXT field.
        iss: {
          type: Sequelize.TEXT
        },
......
        indexes: [{
          fields: ['iss', 'clientId', 'deploymentId', 'user']
        },

Have any one come across this issue and have any fix available?

Detail logs are below.
## yarn start
yarn run v1.22.10
$ env DEBUG=provider:* node index.js
  provider:main Attempting to connect to database +0ms
  provider:database Using Sequelize Database Plugin - Cvmcosta +0ms
  provider:database Dialect: mysql +0ms
(node:11251) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Error during deployment:  DatabaseError [SequelizeDatabaseError]: BLOB/TEXT column 'iss' used in key specification without a key length
    at Query.formatError (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)
    at Query.run (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/sequelize/lib/sequelize.js:619:16
    at async MySQLQueryInterface.addIndex (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:541:12)
    at async Function.sync (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/sequelize/lib/model.js:1367:7)
    at async Sequelize.sync (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/sequelize/lib/sequelize.js:793:35)
    at async Database.setup (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/ltijs-sequelize/dist/DB.js:394:5)
    at async Provider.deploy (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/ltijs/dist/Provider/Provider.js:769:7)
    at async setup (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/index.js:67:3) {
  parent: Error: BLOB/TEXT column 'iss' used in key specification without a key length
      at Packet.asError (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_BLOB_KEY_WITHOUT_LENGTH',
    errno: 1170,
    sqlState: '42000',
    sqlMessage: "BLOB/TEXT column 'iss' used in key specification without a key length",
    sql: 'ALTER TABLE `idtokens` ADD INDEX `idtokens_iss_client_id_deployment_id_user` (`iss`, `clientId`, `deploymentId`, `user`)',
    parameters: undefined
  },
  original: Error: BLOB/TEXT column 'iss' used in key specification without a key length
      at Packet.asError (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/jadavbheda/CD/Projects/NewCanney/ncisd-lti/server/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_BLOB_KEY_WITHOUT_LENGTH',
    errno: 1170,
    sqlState: '42000',
    sqlMessage: "BLOB/TEXT column 'iss' used in key specification without a key length",
    sql: 'ALTER TABLE `idtokens` ADD INDEX `idtokens_iss_client_id_deployment_id_user` (`iss`, `clientId`, `deploymentId`, `user`)',
    parameters: undefined
  },
  sql: 'ALTER TABLE `idtokens` ADD INDEX `idtokens_iss_client_id_deployment_id_user` (`iss`, `clientId`, `deploymentId`, `user`)',
  parameters: undefined
}

Closing server...
Closing connection to the database...
  provider:database Closing connection to database +107ms
  provider:database Closed database connection and removed cronjob +1ms
Shutdown complete.
✨  Done in 0.81s.

**Comment by Cvmcosta** [comment] 2021-03-15 11:53
Hello! Are you using the latest version of ltijs-sequelize? And what is the sample server you are running? `ltijs-demo-server`?

**Comment by jadavbheda** [comment] 2021-03-18 01:07
Yes I am using latest Ltijs-sequelize and yes Ltijs-demo-server

**Comment by Cvmcosta** [comment] 2021-03-18 01:58
Okay, thanks! I will look into it.

**Comment by jadavbheda** [comment] 2021-03-18 02:36
@Cvmcosta - I am not sure about the size of the each fields in database/models. 

But for the timebeing to test things quickly below hack did the trick for me. Hack: For every `indexes` I added length along with the attribute. For example. 

      publickey: (0, _classPrivateFieldGet2.default)(this, _sequelize).define('publickey', {
        kid: {
          type: Sequelize.STRING,
          primaryKey: true
        },

       ....
      }, {
        indexes: [{
          fields: [{
            attribute: 'kid',
            length: 50
          }],
          unique: true
        }]
      }

**Comment by Cvmcosta** [comment] 2021-03-18 11:32
Thanks! Would you mind creating a pull request with these changes? I can then test them and merge if everything is okay

**Comment by jadavbheda** [comment] 2021-03-22 05:44
Sure I will. @Cvmcosta 

Sorry I don't check messages or GitHub quite frequently and hence this delay. I will raise it in about an hour.

**Comment by jadavbheda** [comment] 2021-03-23 01:17
Hi @Cvmcosta , PR link https://github.com/Cvmcosta/ltijs-sequelize/pull/3

**Comment by jonespm** [comment] 2021-03-29 15:03
The schema **seems** like it would have been better to create `iss` (and other fields) as a `STRING` rather than `TEXT` type. These could just be [DataTypes.STRING](https://sequelize.org/master/manual/model-basics.html#strings) and not have this problem. It seems unlikely that these fields will be longer than the length of a `VARCHAR`, and at least for this one (url) only needs at most be 2000 characters. `DataStype.STRING(2000)` maybe, or something even shorter. 

If it's `TEXT`, it will be [fixed at 65K](https://www.navicat.com/en/company/aboutus/blog/1308-choosing-between-varchar-and-text-in-mysql) for each field creating a potential future performance inefficiencies. 

Also, do these all of these fields even need to be indexed? It looks like the PR proposed will should work around this problem but still won't be as optimal as changing the types. But I don't know what it would take to change the schema at this point for anyone currently using this.  

This is probably a different issue that maybe shouldn't hold up this specific one.

**Comment by Cvmcosta** [comment] 2021-03-30 04:09
Hello @jonespm! Thanks for your insight! 
I understand what you mean, i am not really experienced using sequelize so i definitely can improve this in a couple of areas. 

For now i will merge this PR as a fix for the current issue we are facing but i am working on restructuring the database plugin system for Ltijs and that will include releasing a new version of ltijs-sequelize. That will give me more freedom to change stuff in a more meaningful way.

Thanks again!

**Comment by jonespm** [comment] 2021-03-30 05:31
I'm not very familiar with sequelize either still learning more about this library too. 

This package seems interesting, if you model out the database it can generate the sequelize Models out of it. https://github.com/sequelize/sequelize-auto

Thanks for working on this, not sure if we'd have been able to use MongoDB as easily and looking forward to the future changes!

**Comment by Cvmcosta** [comment] 2021-03-31 04:11
Thanks a lot! This package seems very helpful, i'll keep it in mind when working on the new version!

**Comment by Cvmcosta** [comment] 2021-04-06 02:12
I merged this fix. Please confirm that the issue is resolved.

@jonespm I added a auto migration system in the latest version. When i am done with the restructuring i can easily change the field types and much more without affecting current users. Thanks again for the advice.

**Closed by Cvmcosta** 2021-04-06 02:12 UTC
